// ============================================================
// Tuning Generator - Tuning Calculation Utilities
// ============================================================

import { NOTE_NAMES, REFERENCE_PITCHES, JUST_RATIOS, PYTH_RATIOS, TEMPERAMENTS, PRESET_TEMPERAMENTS } from "./constants";

export const ratioToCents = (r) => 1200 * Math.log2(r);
export const centsToRatio = (c) => Math.pow(2, c / 1200);
export const midiToFreq = (m, rn, rf) => rf * Math.pow(2, (m - rn) / 12);

/**
 * Generate a 128-entry MIDI tuning table based on temperament and settings.
 */
export const generateTuningTable = (temp, preset, customOffsets, refPitch) => {
  const { refNote, refFreq } = REFERENCE_PITCHES[refPitch];
  const table = [];
  for (let midi = 0; midi < 128; midi++) {
    const n = midi % 12;
    let cents = 0;
    if (temp === TEMPERAMENTS.EQUAL) cents = n * 100;
    else if (temp === TEMPERAMENTS.JUST) cents = ratioToCents(JUST_RATIOS[n]);
    else if (temp === TEMPERAMENTS.PYTHAGOREAN) cents = ratioToCents(PYTH_RATIOS[n]);
    else if (PRESET_TEMPERAMENTS.includes(temp)) cents = n * 100 + (preset?.offsets?.[n] || 0);
    else if (temp === TEMPERAMENTS.CUSTOM) cents = n * 100 + (customOffsets[n] || 0);
    else cents = n * 100;

    const oct = Math.floor(midi / 12) - 1;
    const freq = midiToFreq(midi, refNote, refFreq) * centsToRatio(cents - n * 100);
    table.push({
      midi,
      note: NOTE_NAMES[n],
      octave: oct,
      cents: oct * 1200 + cents,
      centsInOctave: cents,
      frequency: freq,
      offset: cents - n * 100
    });
  }
  return table;
};

/**
 * Generate a u-he compatible .tun file string from a tuning table.
 * Uses absolute cents from MIDI note 0, matching the format in
 * /Library/Application Support/u-he/Tunefiles/
 */
export const generateTunFile = (table, meta) => {
  const { temperament, preset, refPitch } = meta;
  const { refNote, refFreq } = REFERENCE_PITCHES[refPitch];

  // Cents shift from standard A440-based equal temperament for the chosen reference pitch
  const standardFreq = 440 * Math.pow(2, (refNote - 69) / 12);
  const refShift = 1200 * Math.log2(refFreq / standardFreq);

  const lines = [
    "; Generated by SonicTales Tuning Generator",
    `; Temperament: ${temperament}${preset ? ` - ${preset.name}` : ""}`,
    `; Reference: ${REFERENCE_PITCHES[refPitch].name}`,
    "",
    "[Exact Tuning]"
  ];

  for (let i = 0; i < 128; i++) {
    const absoluteCents = i * 100 + table[i].offset + refShift;
    lines.push(`note ${i}=${absoluteCents.toFixed(2)}`);
  }

  return lines.join("\n");
};
